### ISSUE TITLE
Bench  Get App issue 

### ISSUE THREAD

**Issue by sammish** [frappe/insights#124]
Here the video

https://user-images.githubusercontent.com/12432802/236406481-79bac377-7731-4476-85aa-a47bde2bc428.mov

**Comment by nextchamp-saqib** [comment]
What is your `node` version?

**Comment by sammish** [comment]
![Uploading image.png…]()

**Comment by nextchamp-saqib** [comment]
Update your node version to v14.18+ or v16

**Comment by sammish** [comment]
I received another error after updating the node 

https://user-images.githubusercontent.com/12432802/236609425-ae945a53-2be6-4c50-ae3d-23ce283aa53a.mov

**Comment by sammish** [comment]
Also , this error bench update --reset 

Running build command for insights
warning ../../package.json: No license field
$ cd frontend && yarn build
warning ../../../package.json: No license field
$ vite build --base=/assets/insights/frontend/ && yarn copy-html-entry
failed to load config from /home/frappe/frappe-bench/apps/insights/frontend/vite.config.js
error during build:
Error: Cannot find module 'node:fs'
Require stack:
- /home/frappe/frappe-bench/apps/insights/frontend/node_modules/@vitejs/plugin-vue/dist/index.cjs
- /home/frappe/frappe-bench/apps/insights/frontend/vite.config.js
- /home/frappe/frappe-bench/apps/insights/frontend/node_modules/vite/dist/node/chunks/dep-79892de8.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/frappe/frappe-bench/apps/insights/frontend/node_modules/@vitejs/plugin-vue/dist/index.cjs:5:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object._require.extensions.<computed> [as .js] (file:///home/frappe/frappe-bench/apps/insights/frontend/node_modules/vite/dist/node/chunks/dep-79892de8.js:63989:17)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:433:5)
    at /home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:88:35
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 46233,
  stdout: null,
  stderr: null
}
Done in 19.11s.
Compiling Python files...
$ supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped

**Comment by nextchamp-saqib** [comment]
Did you upgrade to node v16?

According to this https://github.com/vitejs/vite/issues/9113#issuecomment-1184319357 it should work

**Comment by nextchamp-saqib** [comment]
It was a node compatibility issue. I have raised a fix (600f579e4ee4bfd8aeeff975c93e55a16008eaba)

**Comment by sammish** [comment]
Thanks
