### ISSUE TITLE
Unable to install frappe insights with command bench get-app https://github.com/frappe/insights

### ISSUE THREAD

**Issue by Suprazz** [frappe/insights#131]
I get this error:

Could not resolve './NewDialogWithTypes.vue' from src/query/QueryList.vue?vue&type=script&setup=true&lang.jsx
error during build:
Error: Could not resolve './NewDialogWithTypes.vue' from src/query/QueryList.vue?vue&type=script&setup=true&lang.jsx
    at error (/home/frappe/frappe-bench/apps/insights/frontend/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/home/frappe/frappe-bench/apps/insights/frontend/node_modules/rollup/dist/shared/rollup.js:22464:24)
    at /home/frappe/frappe-bench/apps/insights/frontend/node_modules/rollup/dist/shared/rollup.js:22427:26

`Following apps will be installed
1. https://github.com/frappe/insights
Getting insights
$ git clone https://github.com/frappe/insights  --depth 1 --origin upstream
Cloning into 'insights'...
remote: Enumerating objects: 561, done.
remote: Counting objects: 100% (561/561), done.
remote: Compressing objects: 100% (519/519), done.
remote: Total 561 (delta 79), reused 259 (delta 34), pack-reused 0
Receiving objects: 100% (561/561), 14.23 MiB | 42.24 MiB/s, done.
Resolving deltas: 100% (79/79), done.
Installing insights
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/insights
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ cd frontend && yarn install --ignore-engines
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "frappe-ui > @tiptap/extension-color@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-highlight@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-image@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-link@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-mention@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-placeholder@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-table@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-table-cell@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-table-header@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-table-row@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-text-align@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-text-style@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/extension-typography@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/pm@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-keymap@^1.1.2".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-model@^1.8.1".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-state@^1.3.1".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-transform@^1.2.1".
warning "frappe-ui > @tiptap/prosemirror-tables@1.1.4" has unmet peer dependency "prosemirror-view@^1.13.3".
warning "frappe-ui > @tiptap/suggestion@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/vue-3@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/vue-3 > @tiptap/extension-bubble-menu@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "frappe-ui > @tiptap/vue-3 > @tiptap/extension-floating-menu@2.0.3" has unmet peer dependency "@tiptap/core@^2.0.0".
warning "vue3-drr-grid-layout > @interactjs/actions@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning "vue3-drr-grid-layout > @interactjs/actions@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning "vue3-drr-grid-layout > @interactjs/auto-start@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning "vue3-drr-grid-layout > @interactjs/auto-start@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning "vue3-drr-grid-layout > @interactjs/dev-tools@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning "vue3-drr-grid-layout > @interactjs/modifiers@1.10.17" has unmet peer dependency "@interactjs/core@1.10.17".
warning "vue3-drr-grid-layout > @interactjs/modifiers@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
warning "vue3-drr-grid-layout > @interactjs/modifiers > @interactjs/snappers@1.10.17" has unmet peer dependency "@interactjs/utils@1.10.17".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 7.36s.
Done in 7.84s.
$ bench build --app insights
✔ Application Assets Linked

yarn run v1.22.19
$ node esbuild --production --apps insights --run-build-command
File                                                        Size

 DONE  Total Build Time: 695.231ms

clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration

Running build command for insights
$ cd frontend && yarn build
$ vite build --base=/assets/insights/frontend/ && yarn copy-html-entry
vite v2.9.15 building for production...
✓ 143 modules transformed.
Could not resolve './NewDialogWithTypes.vue' from src/query/QueryList.vue?vue&type=script&setup=true&lang.jsx
error during build:
Error: Could not resolve './NewDialogWithTypes.vue' from src/query/QueryList.vue?vue&type=script&setup=true&lang.jsx
    at error (/home/frappe/frappe-bench/apps/insights/frontend/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/home/frappe/frappe-bench/apps/insights/frontend/node_modules/rollup/dist/shared/rollup.js:22464:24)
    at /home/frappe/frappe-bench/apps/insights/frontend/node_modules/rollup/dist/shared/rollup.js:22427:26
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:436:5)
    at /home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:88:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 110943,
  stdout: null,
  stderr: null
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Command failed: yarn build
    at checkExecSyncError (node:child_process:871:11)
    at execSync (node:child_process:943:15)
    at run_build_command_for_apps (/home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:436:5)
    at /home/frappe/frappe-bench/apps/frappe/esbuild/esbuild.js:88:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 110943,
  stdout: null,
  stderr: null
}

Node.js v18.12.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 86, in build
    bundle(mode, apps=apps, hard_link=hard_link, verbose=verbose, skip_frappe=skip_frappe)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/build.py", line 257, in bundle
    frappe.commands.popen(command, cwd=frappe_app_path, env=get_node_env(), raise_err=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 98, in popen
    raise subprocess.CalledProcessError(return_, command)
subprocess.CalledProcessError: Command 'yarn run production --apps insights --run-build-command' returned non-zero exit status 1.
ERROR:
subprocess.CalledProcessError: Command 'bench build --app insights' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 412, in get_app
    install_resolved_deps(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 514, in install_resolved_deps
    app.install_resolved_apps(skip_assets=skip_assets, verbose=verbose)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 255, in install_resolved_apps
    self.install(*args, **kwargs, resolved=True)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 242, in install
    install_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 586, in install_app
    build_assets(bench_path=bench_path, app=app)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/bench.py", line 351, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError
`

**Comment by nextchamp-saqib** [comment]
There was an invalid import that I missed. Check now
