### ISSUE TITLE
Insights Installation

### ISSUE THREAD

**Issue by AhmadReda** [frappe/insights#132]
I am trying to install Frappe Insight on the production server 
I have my own site has an application built on top of frappe
I am following the coming steps bellow:
1- bench get-app https://github.com/frappe/insights
2- bench --site <my_site_name> install-app insights
while executing command number 2 I get this error message:

Installing insights...
An error occurred while installing insights: Module import failed for Insights Settings, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'redis_cache' from 'frappe.utils.caching' (/home/kaizen/frappe-bench/apps/frappe/frappe/utils/caching.py)
Traceback (most recent call last):
  File "apps/frappe/frappe/modules/utils.py", line 240, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/insights/insights/insights/doctype/insights_settings/insights_settings.py", line 8, in <module>
    from insights.api.subscription import get_subscription_key
  File "apps/insights/insights/api/__init__.py", line 8, in <module>
    from frappe.utils.caching import redis_cache
ImportError: cannot import name 'redis_cache' from 'frappe.utils.caching' (apps/frappe/frappe/utils/caching.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 416, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 294, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 81, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 408, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 493, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 244, in load_doctype_module
    raise ImportError(msg) from e
ImportError: Module import failed for Insights Settings, the DocType you're trying to open might be deleted.<br> Error: cannot import name 'redis_cache' from 'frappe.utils.caching' (apps/frappe/frappe/utils/caching.py)

**Comment by nextchamp-saqib** [comment]
Your frappe version must be old. Update to v14.33.0 and try again. Let me know if it works.

**Comment by nextchamp-saqib** [comment]
Pretty sure updating would fix
