### ISSUE TITLE
An error occurred while installing insights: Insights Data Source Site DB not found

### ISSUE THREAD

**Issue by jcruzram** [frappe/insights#134]
An error occurred while installing insights: Insights Data Source Site DB not found
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 416, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 304, in install_app
    frappe.get_attr(after_install)()
  File "apps/insights/insights/setup/__init__.py", line 17, in after_install
    sync_site_tables()
  File "apps/insights/insights/setup/__init__.py", line 57, in sync_site_tables
    doc = frappe.get_doc("Insights Data Source", "Site DB")
  File "apps/frappe/frappe/__init__.py", line 1184, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 525, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 493, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Insights Data Source Site DB not found

**Comment by nextchamp-saqib** [comment]
fixed: de867793e00efed1f41f87a2f4b15c2953d5b11e
