### ISSUE TITLE
Error While accessing insights home page

### ISSUE THREAD

**Issue by chechani** [frappe/insights#146]
getting this error while going to insights home page
```
Traceback (most recent call last):
  File "apps/frappe/frappe/handler.py", line 75, in execute_cmd
    method = get_attr(cmd)
  File "apps/frappe/frappe/handler.py", line 256, in get_attr
    method = frappe.get_attr(cmd)
  File "apps/frappe/frappe/__init__.py", line 1640, in get_attr
    return getattr(get_module(modulename), methodname)
AttributeError: module 'insights.api' has no attribute 'get_onboarding_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 83, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 77, in execute_cmd
    frappe.throw(_("Failed to get method for command {0} with {1}").format(cmd, e))
  File "apps/frappe/frappe/__init__.py", line 550, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 518, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 467, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Failed to get method for command insights.api.get_onboarding_status with module 'insights.api' has no attribute 'get_onboarding_status'
```
version
```
ERPNext: v14.x.x-develop () (develop)

Frappe Framework: v15.x.x-develop () (develop)

Gameplan: v0.0.1 (main)

Frappe Insights: v1.0.0 (develop)
```

**Comment by nextchamp-saqib** [comment]
<img width="1440" alt="CleanShot 2023-07-29 at 00 28 00@2x" src="https://github.com/frappe/insights/assets/25369014/4dae97f6-ed33-4856-a431-90508385a6c4">

There's no reference to `get_onboarding_status` in the codebase. 🤔
can you run `bench build --app insights` and check?

**Comment by chechani** [comment]
bench build --app insights solved the issue, but apparently bench build did not solve it.


you can close the ticket
