### ISSUE TITLE
Cannot add queries in charts

### ISSUE THREAD

**Issue by michellealva** [frappe/insights#155]
<img width="1669" alt="image" src="https://github.com/frappe/insights/assets/50285544/df88a969-b960-4e55-b6d7-0c93e3e6f537">

```
TypeError: Cannot read properties of null (reading 'hasOwnProperty')
    at B (ListPicker-c3999a67.js:1:1289)
    at al.fn (ListPicker-c3999a67.js:1:1221)
    at al.run (frappe-ui-72bd7683.js:1:5946)
    at get value [as value] (frappe-ui-72bd7683.js:1:15063)
    at al.fn (ListPicker-c3999a67.js:1:1875)
    at al.run (frappe-ui-72bd7683.js:1:5946)
    at get value [as value] (frappe-ui-72bd7683.js:1:15063)
    at ListPicker-c3999a67.js:1:3288
    at Object.r [as default] (frappe-ui-72bd7683.js:1:18617)
    at tu (frappe-ui-72bd7683.js:1:90237)
```

**Comment by nextchamp-saqib** [comment]
Cannot replicate, reopen if you can replicate it
