### ISSUE TITLE
Installation Failing on Frappe Cloud

### ISSUE THREAD

**Issue by ahmadpak** [frappe/insights#179]
Every time I try to deploy frappe insight on Frappe Cloud it fails

bench get-app insights
Getting insights
$ git clone file:///home/frappe/context/apps/insights  --depth 1 --origin upstream
Cloning into 'insights'...
Ignoring dependencies of file:///home/frappe/context/apps/insights. To install dependencies use --resolve-deps
Installing insights
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/insights
WARNING: There was an error checking the latest version of pip.
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error insights-frontend@0.0.0: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.19.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR:
Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/cli.py", line 127, in cli
    bench_command()
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/commands/make.py", line 159, in get_app
    get_app(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 242, in install
    install_app(
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/app.py", line 581, in install_app
    bench.run("yarn install", cwd=app_path)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/frappe/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError
bench.exceptions.CommandFailedError
INFO: A newer version of bench is available: 5.15.2 → 5.17.2
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/insights `#stage-apps-insights`]: exit code: 1
> [stage-0 36/41] RUN --mount=type=cache,target=/home/frappe/.cache,uid=1000,gid=1000 --mount=type=bind,source=apps/insights,target=/home/frappe/context/apps/insights bench get-app file:///home/frappe/context/apps/insights `#stage-apps-insights`:
executor failed running [/bin/sh -c bench get-app file:///home/frappe/context/apps/insights `#stage-apps-insights`]: exit code: 1

**Comment by nextchamp-saqib** [comment]
Update your node version to >=16
That should fix the issue
