### ISSUE TITLE
Error while installing app

### ISSUE THREAD

**Issue by anupamvs** [frappe/insights#186]
Frappe - V14
Database - Postgress

Installing insights...
Updating DocTypes for insights      : [===============================         ] 78%Syntax error in query:
CREATE INDEX IF NOT EXISTS "data_source_table_index" ON "tabInsights Table" (""data_source"", ""table"") 
An error occurred while installing insights: zero-length delimited identifier at or near """"
LINE 1: ..."data_source_table_index" ON "tabInsights Table" (""data_sou...
                                                             ^

Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 415, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 294, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 109, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1246, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 409, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 496, in run_module_method
    getattr(module, method)()
  File "apps/insights/insights/insights/doctype/insights_table/insights_table.py", line 61, in on_doctype_update
    frappe.db.add_index(
  File "apps/frappe/frappe/database/postgres/database.py", line 343, in add_index
    self.sql_ddl(f'CREATE INDEX IF NOT EXISTS "{index_name}" ON `{table_name}` ("{fields_str}")')
  File "apps/frappe/frappe/database/database.py", line 378, in sql_ddl
    self.sql(query, debug=debug)
  File "apps/frappe/frappe/database/postgres/database.py", line 199, in sql
    return super().sql(modify_query(query), modify_values(values), *args, **kwargs)
  File "apps/frappe/frappe/database/database.py", line 220, in sql
    self._cursor.execute(query, values)
psycopg2.errors.SyntaxError: zero-length delimited identifier at or near """"
LINE 1: ..."data_source_table_index" ON "tabInsights Table" (""data_sou...

**Comment by nextchamp-saqib** [comment]
fixed: 4ed833e7bd0f846ed591a24bb68869a2bb75bdef

**Comment by Syed2627** [comment]
![image](https://github.com/frappe/insights/assets/79511987/7ed8c6ad-a2b7-418e-bbc4-bd5b88e28fdf)

@nextchamp-saqib I have got this error can you please tell me what's the issue is
