### ISSUE TITLE
i get this error 

### ISSUE THREAD

**Issue by ox4khenaton** [frappe/insights#195]
ERROR: [Errno 2] No such file or directory: '/home/ilyes/frappe-bench/apps/insights/setup.py'
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 121, in cli
    raise e
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 111, in cli
    bench_command()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 156, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 420, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 110, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 217, in install
    app_name = get_app_name(self.bench.name, self.app_name)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/app.py", line 224, in get_app_name
    with open(app_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ilyes/frappe-bench/apps/insights/setup.py'

**Comment by nextchamp-saqib** [comment]
This seems to be an invalid issue. Please remove insights app and try installing again
