### ISSUE TITLE
Version number '2.0.x' does not match PEP 440 rules

### ISSUE THREAD

**Issue by Suprazz** [frappe/insights#213]
I'm trying to install latest version and I got this error

root@ERPNextV14:/home/frappe/frappe-bench# bench get-app https://github.com/frappe/insights
Getting insights
$ git clone https://github.com/frappe/insights  --depth 1 --origin upstream
Cloning into 'insights'...
remote: Enumerating objects: 686, done.
remote: Counting objects: 100% (686/686), done.
remote: Compressing objects: 100% (629/629), done.
remote: Total 686 (delta 92), reused 373 (delta 49), pack-reused 0
Receiving objects: 100% (686/686), 20.03 MiB | 19.50 MiB/s, done.
Resolving deltas: 100% (92/92), done.
Ignoring dependencies of https://github.com/frappe/insights. To install dependencies use --resolve-deps
Installing insights
$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/insights
WARNING: Ignoring invalid distribution -edis (/home/frappe/frappe-bench/env/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ip (/home/frappe/frappe-bench/env/lib/python3.10/site-packages)
  error: subprocess-exited-with-error

  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-cdyep_sw/overlay/lib/python3.10/site-packages/flit_core/buildapi.py", line 49, in prepare_metadata_for_build_wheel
          metadata = make_metadata(module, ini_info)
        File "/tmp/pip-build-env-cdyep_sw/overlay/lib/python3.10/site-packages/flit_core/common.py", line 425, in make_metadata
          md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
        File "/tmp/pip-build-env-cdyep_sw/overlay/lib/python3.10/site-packages/flit_core/common.py", line 235, in get_info_from_module
          res['version'] = check_version(version)
        File "/tmp/pip-build-env-cdyep_sw/overlay/lib/python3.10/site-packages/flit_core/common.py", line 258, in check_version
          version = normalise_version(version)
        File "/tmp/pip-build-env-cdyep_sw/overlay/lib/python3.10/site-packages/flit_core/versionno.py", line 86, in normalise_version
          raise InvalidVersion("Version number {!r} does not match PEP 440 rules"
      flit_core.common.InvalidVersion: Version number '2.0.x' does not match PEP 440 rules
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
ERROR: /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/insights
subprocess.CalledProcessError: Command '/home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/insights ' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/usr/local/lib/python3.10/dist-packages/bench/commands/make.py", line 167, in get_app
    get_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 242, in install
    install_app(
  File "/usr/local/lib/python3.10/dist-packages/bench/app.py", line 573, in install_app
    bench.run(
  File "/usr/local/lib/python3.10/dist-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/usr/local/lib/python3.10/dist-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/insights

**Comment by nextchamp-saqib** [comment]
Reverted the version change for now. Should be fixed
