### ISSUE TITLE
While trying to update the app i got ERROR: yarn install --check-files

### ISSUE THREAD

**Issue by Sendipad** [frappe/insights#239]
```
yarn install v1.22.22
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Couldn't find package "frappe-ui@0.1.35" required by "insights-frontend@0.0.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: yarn install --check-files
subprocess.CalledProcessError: Command 'yarn install --check-files' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/commands/setup.py", line 230, in setup_requirements
    bench.setup.requirements(apps=apps)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/utils/render.py", line 105, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/bench.py", line 464, in requirements
    app = App(path_to_app, bench=self.bench, to_clone=False).install(
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/app.py", line 255, in install
    install_app(
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/app.py", line 915, in install_app
    bench.run(yarn_install, cwd=app_path)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/erpnext/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 169, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: yarn install --check-files

```

**Comment by nextchamp-saqib** [comment]
Are you still facing this issue? I haven't been able to replicate it on any site/local instance. It seems to be an issue with the `frappe-ui` version which has been upgraded recently. Try updating the app and check if you are still facing the issue.
