### ISSUE TITLE
ERROR: git clone https://github.com/frappe/insights.git  --depth 1 --origin upstream

### ISSUE THREAD

**Issue by nguyenth18** [frappe/insights#249]
Hi team,

After removing insights, I tried to reinstall it but getting below error:

erp@DESKTOP-JQA80O8:~/frappe-bench$ bench get-app insights
Getting insights
$ git clone https://github.com/frappe/insights.git  --depth 1 --origin upstream
Cloning into 'insights'...
remote: Enumerating objects: 709, done.
remote: Counting objects: 100% (709/709), done.
remote: Compressing objects: 100% (645/645), done.
error: 5955 bytes of body are still expected 185.00 KiB/s   
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
ERROR: git clone https://github.com/frappe/insights.git  --depth 1 --origin upstream
subprocess.CalledProcessError: Command 'git clone https://github.com/frappe/insights.git  --depth 1 --origin upstream' returned non-zero exit status 128.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/erp/.local/lib/python3.10/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/erp/.local/lib/python3.10/site-packages/bench/commands/make.py", line 181, in get_app
    get_app(
  File "/home/erp/.local/lib/python3.10/site-packages/bench/app.py", line 770, in get_app
    app.get()
  File "/home/erp/.local/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/erp/.local/lib/python3.10/site-packages/bench/app.py", line 203, in get
    self.bench.run(
  File "/home/erp/.local/lib/python3.10/site-packages/bench/bench.py", line 48, in run
    return exec_cmd(cmd, cwd=cwd or self.cwd, _raise=_raise)
  File "/home/erp/.local/lib/python3.10/site-packages/bench/utils/__init__.py", line 178, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: git clone https://github.com/frappe/insights.git  --depth 1 --origin upstream

**Comment by nguyenth18** [comment]
I am able to get the app on the next day, I think it was due to unstable internet connection.
