### ISSUE TITLE
Cannot import Data from CSV

### ISSUE THREAD

**Issue by zaheer-srushty** [frappe/insights#325]
This is the error being reported when I try to import a CSV file.

``` python
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/insights/insights/decorators.py", line 34, in wrapper
    return function(*args, **kwargs)
  File "apps/insights/insights/decorators.py", line 165, in wrapper
    return function(*args, **kwargs)
  File "apps/insights/insights/decorators.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "apps/insights/insights/api/__init__.py", line 157, in import_csv_data
    InsightsTablev3.create(ds.name, table_name)
AttributeError: type object 'InsightsTablev3' has no attribute 'create'
```

**Comment by nextchamp-saqib** [comment]
fixed with 003dd083254e93cbe7e6af59ed18e76c09472f5e
