### ISSUE TITLE
DB password special characters create ValueError: Port could not be cast to integer value

### ISSUE THREAD

**Issue by P-Godfroid** [frappe/insights#345]
Hello,
Brand new Insight installation.
![image](https://github.com/user-attachments/assets/6751f68d-ae38-4a8e-b291-08d20e29d96b)

When I try to connect to my first DB, this error occurs :
![image](https://github.com/user-attachments/assets/f54da0d7-e22f-4a79-843c-d4ea593e4b11)

`Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1781, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/insights/insights/decorators.py", line 18, in wrapper
    return function(*args, **kwargs)
  File "apps/insights/insights/decorators.py", line 167, in wrapper
    return function(*args, **kwargs)
  File "apps/insights/insights/api/data_sources.py", line 419, in test_connection
    return ds.test_connection(raise_exception=True)
  File "apps/insights/insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py", line 215, in test_connection
    raise e
  File "apps/insights/insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py", line 209, in test_connection
    db = self._get_ibis_backend()
  File "apps/insights/insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py", line 174, in _get_ibis_backend
    db: BaseBackend = self._get_db_connection()
  File "apps/insights/insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py", line 189, in _get_db_connection
    return ibis.connect(connection_string)
  File "env/lib/python3.10/site-packages/ibis/backends/__init__.py", line 1444, in connect
    return backend._from_url(parsed, **kwargs)
  File "env/lib/python3.10/site-packages/ibis/backends/mysql/__init__.py", line 66, in _from_url
    "port": url.port or None,
  File "/usr/lib/python3.10/urllib/parse.py", line 185, in port
    raise ValueError(f"Port could not be cast to integer value as {port!r}")
ValueError: Port could not be cast to integer value as '89T6gLr'`

The issue comes not from the Port regardless of what the error says.
It is caused by the presence of special characters in the db password as I was able to overcome the error with a new sql user with a simpler password.
In my case my password contains these characters : ?Qw:/j8   , I guess the issue should be / .

Mysql Password can theorically contains any character so it is indeed an issue.

**Comment by nextchamp-saqib** [comment]
pushed a fix (440b9393d5fcc946e0945ebb71a44c40e832729a)
can you switch to `develop` branch and check if the issue is fixed?

**Comment by P-Godfroid** [comment]
> pushed a fix ([440b939](https://github.com/frappe/insights/commit/440b9393d5fcc946e0945ebb71a44c40e832729a)) can you switch to `develop` branch and check if the issue is fixed?

It is indeed fixed.
Thank you
