### ISSUE TITLE
DB Connexion : Special Character in Database Name generates ParseError

### ISSUE THREAD

**Issue by P-Godfroid** [frappe/insights#348]
Hello, this time it is the database name field which can cause an issue.

Traceback (most recent call last):
  File "env/lib/python3.10/site-packages/sqlglot/parser.py", line 1422, in parse_into
    return self._parse(parser, raw_tokens, sql)
  File "env/lib/python3.10/site-packages/sqlglot/parser.py", line 1464, in _parse
    self.raise_error("Invalid expression / Unexpected token")
  File "env/lib/python3.10/site-packages/sqlglot/parser.py", line 1505, in raise_error
    raise error
sqlglot.errors.ParseError: Invalid expression / Unexpected token. Line 1, Col: 8.
  silicon-ioi

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1781, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/insights/insights/decorators.py", line 18, in wrapper
    return function(*args, **kwargs)
  File "apps/insights/insights/decorators.py", line 167, in wrapper
    return function(*args, **kwargs)
  File "apps/insights/insights/api/data_sources.py", line 419, in test_connection
    return ds.test_connection(raise_exception=True)
  File "apps/insights/insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py", line 215, in test_connection
    raise e
  File "apps/insights/insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py", line 210, in test_connection
    db.list_tables()
  File "env/lib/python3.10/site-packages/ibis/backends/mysql/__init__.py", line 339, in list_tables
    table_loc = self._to_sqlglot_table(table_loc)
  File "env/lib/python3.10/site-packages/ibis/backends/sql/__init__.py", line 588, in _to_sqlglot_table
    table = sg.parse_one(database, into=sg.exp.Table, dialect=self.dialect)
  File "env/lib/python3.10/site-packages/sqlglot/__init__.py", line 134, in parse_one
    result = dialect.parse_into(into, sql, **opts)
  File "env/lib/python3.10/site-packages/sqlglot/dialects/dialect.py", line 927, in parse_into
    return self.parser(**opts).parse_into(expression_type, self.tokenize(sql), sql)
  File "env/lib/python3.10/site-packages/sqlglot/parser.py", line 1427, in parse_into
    raise ParseError(
sqlglot.errors.ParseError: Failed to parse 'silicon-ioi' into <class 'sqlglot.expressions.Table'>

In my case it is the - which causes the problem. 

Frappe sites db-name can contains underscores and hyphens (no whitespace) and maybe several other special characters.

**Comment by nextchamp-saqib** [comment]
Fixed: 015e2130b5b9f648a0b26eb98ce53b480a59d384

**Comment by P-Godfroid** [comment]
> Fixed: [015e213](https://github.com/frappe/insights/commit/015e2130b5b9f648a0b26eb98ce53b480a59d384)

Hello,

I confirm the fix works properly
