### ISSUE TITLE
Unable to add query to dashboard from query view.

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/insights#48]
https://screenrec.com/share/vLXGc8BSt0

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 58, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1584, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 310, in run_doc_method
    response = doc.run_method(method, **args)
  File "apps/frappe/frappe/model/document.py", line 925, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1269, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1251, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 922, in fn
    return method_object(*args, **kwargs)
  File "apps/insights/insights/insights/doctype/insights_query_chart/insights_query_chart.py", line 25, in add_to_dashboard
    dashboard_doc.add_chart(self.name, layout)  # saves the dashboard
AttributeError: 'InsightsDashboard' object has no attribute 'add_chart'
```

**Comment by nextchamp-saqib** [comment]
Fixed with https://github.com/frappe/insights/commit/6bda48768777f8069e98355ee4e96c66c81629cf
