### ISSUE TITLE
Temporary table error

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/insights#56]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 58, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1597, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/handler.py", line 304, in run_doc_method
    response = doc.run_method(method)
  File "apps/frappe/frappe/model/document.py", line 925, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1269, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1251, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 922, in fn
    return method_object(*args, **kwargs)
  File "apps/insights/insights/insights/doctype/insights_table/insights_table.py", line 26, in get_preview
    return data_source.get_table_preview(self.table)
  File "apps/insights/insights/insights/doctype/insights_data_source/insights_data_source.py", line 108, in get_table_preview
    return self.db.get_table_preview(table, limit)
  File "apps/insights/insights/insights/doctype/insights_data_source/sources/query_store.py", line 131, in get_table_preview
    self.create_temporary_table(table)
  File "apps/insights/insights/insights/doctype/insights_data_source/sources/query_store.py", line 112, in create_temporary_table
    self._execute(insert_records, values=result)
  File "apps/insights/insights/insights/doctype/insights_data_source/sources/query_store.py", line 127, in _execute
    frappe.log_error(f"Error fetching data from QueryStore: {e}")
  File "apps/frappe/frappe/__init__.py", line 2237, in log_error
    return error_log.insert(ignore_permissions=True)
  File "apps/frappe/frappe/model/document.py", line 256, in insert
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 525, in _validate
    self._validate_length()
  File "apps/frappe/frappe/model/base_document.py", line 907, in _validate_length
    self.throw_length_exceeded_error(df, max_length, value)
  File "apps/frappe/frappe/model/base_document.py", line 941, in throw_length_exceeded_error
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.CharacterLengthExceededError: Error Log 355: 'Title' (Error fetching data from QueryStore: (1292, "Incorrect datetime value: 'Oct 22' for column `_02cd5c47d5cfc415`.`QRY-0154`.`creation` at row 1")) will get truncated, as max characters allowed is 140
```

**Comment by nextchamp-saqib** [comment]
Fixed: 0023c42c98447d5976452b6747f16fb1de29a37e
